name: Push Releases

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release Tag'
        required: true
      release_title:
        description: 'Release Title'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0

    - name: Set release tag and title
      id: set_release_tag_title
      run: |
        echo "::set-output name=release_tag::${{ github.event.inputs.release_tag }}"
        echo "::set-output name=release_title::${{ github.event.inputs.release_title }}"
      shell: bash

    - name: Zip folder
      run: |
        sudo apt-get install -y zip
        zip -r ODB.zip ODB
      working-directory: ${{ github.workspace }}

    - name: Set up Git
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Create release
      run: |
        release_tag="${{ steps.set_release_tag_title.outputs.release_tag }}"
        release_title="${{ steps.set_release_tag_title.outputs.release_title }}"
        commit_history=$(git log -5 --graph --oneline)
        changelog=$(cat Changelog.md)

        if gh release view "$release_tag" &>/dev/null; then
          gh release delete "$release_tag" --yes
        fi

        gh release create "$release_tag" ./ODB.zip --title "$release_title" --notes "$changelog"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
